 spring:
   cache:
     type: redis
     redis:
#       host: cache
       host: localhost
       port: 6379
     jpa:
        generate-ddl: true
        properties:
            hibernate:
                jdbc:
                  time_zone: UTC
                ddl-auto: validate
                show_sql: true
##                cache:
##                  use_query_cache: true
##                  use_second_level_cache: true
##                  factory_class: org.redisson.hibernate.RedissonRegionFactory
##                  redisson:
##                    fallback: true
##                    config: "src/main/resources/rediss/redisson.yaml"